name: Build and Deploy to DO

on:
  push:
    branches: 
      - new_runners

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: DigitalOcean App Platform deployment
      uses: digitalocean/app_action@v1.1.5
      with:
        app_name: dk64-randomizer
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
